### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by RonDen** [MegamanZeroX/SoftwareEngineering#36]
### 成绩管理

**职责说明**：

> 成绩管理子系统管理学生的**课程成绩**并提供**课程评价**功能。教师可**提交成绩**，**打印成绩**，**下载成绩**汇总。学生可**查看课程成绩**，查看个人已选课程成绩汇总信息，并可下载打印。最后系统应能够向管理员提供**查询界面**和**各类报表**，**统计**学生成绩情况。系统提供基于Web的访问，同时支持学生通过手机查看个人成绩。

- [x] 课程信息的构建。
- [ ] 学生课程成绩信息的构建。包括数据的导入。
- [ ] 实现教学评价功能。
- [ ] 实现按学号筛选，找到学生选修的课程以及对应成绩得分。包括平时分和最终考试得分。实现学生的个人成绩查询。
- [ ] 实现学生个人的成绩汇总和分析界面。
- [ ] 实现教师通过Excel表格上传成绩的功能。提供上传成绩的Excel表格模板下载地址。
- [ ] 提供老师对自己所教学班级的成绩分析功能。根据老师筛选出所教课程，并在界面上显示各个班级的成绩情况（需要展现出重要统计信息，如平均分，不及格率、优秀率等，绘制相应的分布图表。直方图和饼图）。在此页面提供导出PDF和班级成绩Excel表格的功能。导出方便打印或进一步分析。
- [ ] 提供关于专业和行政班的查询和统计分析功能。导出成绩信息为Excel表，便于辅导员等相关人员进行分析。
- [ ] 对于系统管理员，提供各专业级别的成绩统计分析功能。要求展示重要信息如GPA等，绘制相应的图表（分布图和趋势图）。提供导出图表功能PDF和Excel。

**Comment by RonDen** [comment]
欢迎大家来丰富，把里面都打上勾勾 ✔️ ✔️ 😄
